trigger:
- main

# strategy:
#  matrix:
#   linux:
#     operatingSystem: 'ubuntu-latest'
#   windows:
#     operatingSystem: 'windows-latest'

pool:
  # vmImage: ubuntu-latest
  name: Test Agent

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo Do the Build
- stage: DevDeploy
  jobs:
  # - job: BuildJob
  #   steps:
  #   - script: echo "Start Dev Deploy"
  - deployment: DevDeployJob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to Dev
- stage: QADeploy
  jobs:
  # - job: BuildJob
  #   steps:
  #   - script: echo "Start Dev Deploy"
  - deployment: QADeployJob
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to QA


# steps:
# - script: echo RRunning one $(operatingSystem)!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
