# Starter pipeline
trigger:
- main

pool:
  vmImage: ubuntu-latest  # Using Microsoft-hosted Ubuntu agent

stages:
- stage: Setup
  jobs:
  - job: AzureSetup
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azure-resource-manager-service-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Logging into Azure..."
          az account show --output table

          echo "Checking if resource group exists..."
          if ! az group show --name terraform-backend-rg --output none; then
            echo "Resource group not found. Creating..."
            az group create --name terraform-backend-rg --location westeurope
          else
            echo "Resource group exists."
          fi

          echo "Checking if storage account exists..."
          if ! az storage account show --name storageaccjimsonxyz --resource-group terraform-backend-rg --output none; then
            echo "Storage account not found. Creating..."
            az storage account create \
              --name storageaccjimsonxyz \
              --resource-group terraform-backend-rg \
              --sku Standard_RAGRS \
              --kind StorageV2 \
              --location westeurope \
              --encryption-services blob \
              --https-only true \
              --allow-blob-public-access false \
              --min-tls-version TLS1_2
          else
            echo "Storage account exists."
          fi

          echo "Creating storage container if it doesn't exist..."
          az storage container create \
            --name storageaccjimsoncontainer \
            --account-name storageaccjimsonxyz \
            --auth-mode login
      displayName: 'Create Azure Resources'

    - task: DownloadSecureFile@1
      name: publickey
      inputs:
        secureFile: 'azure_rsa.pub'
        retryCount: '5'
    - bash: |
            # Read and clean the public key (remove comments, whitespace, newlines)
            PUBLIC_KEY_CONTENT=$(cat $(publickey.secureFilePath) | tr -d '\n' | awk '{$1=$1};1')
            echo "##vso[task.setvariable variable=PUBLIC_KEY_CONTENT]${PUBLIC_KEY_CONTENT}"
            
            # Create a clean key file in the working directory
            mkdir -p $(TF_WORKING_DIR)
            echo "${PUBLIC_KEY_CONTENT}" > $(TF_WORKING_DIR)/cleaned_ssh_key.pub
            echo "##vso[task.setvariable variable=SSH_PUBLIC_KEY_PATH]$(TF_WORKING_DIR)/cleaned_ssh_key.pub"
            
            # Verify key format
            echo "SSH Public Key Content:"
            cat $(SSH_PUBLIC_KEY_PATH)
            ssh-keygen -l -f $(SSH_PUBLIC_KEY_PATH)
      displayName: 'Process SSH public key'

- stage: Terraform
  jobs:
  - job: TerraformJob
    steps:
    - task: TerraformCLI@2
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
        # commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
        backendType: 'azurerm'
        backendServiceArm: 'azure-resource-manager-service-connection'
        backendAzureRmTenantId: '4d143b55-605d-4af2-a581-12ee448bba20'
        backendAzureRmSubscriptionId: 'fbccdf0c-3db4-454b-a6f3-0713e306b7f5'
        backendAzureRmResourceGroupName: 'terraform-backend-rg'
        backendAzureRmResourceGroupLocation: 'westeurope'
        backendAzureRmStorageAccountName: 'storageaccjimsonxyz'
        backendAzureRmContainerName: 'storageaccjimsoncontainer'
        backendAzureRmKey: 'kubernetes-dev.tfstate'
        allowTelemetryCollection: true
    - task: TerraformCLI@2
      inputs:
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
        environmentServiceName: 'azure-resource-manager-service-connection'
        commandOptions: '-auto-approve -var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key="$(SSH_PUBLIC_KEY_PATH)" -var node_count=2 '
        allowTelemetryCollection: true


    - script: |
        echo "Add other tasks to build, test, and deploy your project."
        echo "See https://aka.ms/yaml"
      displayName: 'Run a multi-line script'
