trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  TF_WORKING_DIR: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
  CLEAN_KEY_PATH: '$(System.DefaultWorkingDirectory)/cleaned_ssh_key.pub'

stages:
- stage: Setup
  jobs:
  - job: AzureSetup
    steps:
    - task: DownloadSecureFile@1
      name: publickey
      inputs:
        secureFile: 'azure_rsa.pub'
    
    - bash: |
        # Validate and clean the key file
        if ! ssh-keygen -l -f $(publickey.secureFilePath); then
          echo "##vso[task.logissue type=error]Invalid SSH key format"
          exit 1
        fi
        
        # Create cleaned version with proper Unix line endings
        sed 's/\r$//' $(publickey.secureFilePath) > $(CLEAN_KEY_PATH)
        chmod 644 $(CLEAN_KEY_PATH)
        
        # Upload cleaned key as pipeline artifact
        echo "##vso[artifact.upload containerfolder=sshkey;artifactname=cleaned_key]$(CLEAN_KEY_PATH)"
      displayName: 'Prepare SSH Key'

- stage: Terraform
  dependsOn: Setup
  jobs:
  - job: TerraformJob
    steps:
    - download: current
      artifact: cleaned_key
      patterns: '**/cleaned_ssh_key.pub'
      
    - bash: |
        SSH_KEY_PATH=$(Pipeline.Workspace)/cleaned_key/cleaned_ssh_key.pub
        echo "##vso[task.setvariable variable=SSH_KEY_PATH]$SSH_KEY_PATH"
        echo "Using SSH key at: $SSH_KEY_PATH"
        ls -la $SSH_KEY_PATH
        echo "Key content (first line only):"
        head -n 1 $SSH_KEY_PATH
      displayName: 'Prepare Key Path'
    
    - task: TerraformCLI@2
      inputs:
        command: 'init'
        workingDirectory: '$(TF_WORKING_DIR)'
        backendType: 'azurerm'
        backendServiceArm: 'azure-resource-manager-service-connection'
        backendAzureRmResourceGroupName: 'terraform-backend-rg'
        backendAzureRmStorageAccountName: 'storageaccjimsonxyz'
        backendAzureRmContainerName: 'storageaccjimsoncontainer'
        backendAzureRmKey: 'kubernetes-dev.tfstate'

    - task: TerraformCLI@2
      inputs:
        command: 'apply'
        workingDirectory: '$(TF_WORKING_DIR)'
        environmentServiceName: 'azure-resource-manager-service-connection'
        commandOptions: '-auto-approve -var="client_id=$(client_id)" -var="client_secret=$(client_secret)" -var="ssh_public_key=$(SSH_KEY_PATH)" -var="node_count=$(node_count)"'
