# Starter pipeline
trigger:
- main

pool:
  vmImage: ubuntu-latest  # Using self-hosted Windows agent

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo "Setting correct subscription..."
    az account set --subscription "fbccdf0c-3db4-454b-a6f3-0713e306b7f5"

    echo "Checking if resource group exists..."
    if ! az group show --name terraform-backend-rg --output none; then
      echo "Resource group not found. Creating..."
      az group create --name terraform-backend-rg --location westeurope
    else
      echo "Resource group exists."
    fi

    echo "Checking if storage account exists..."
    if ! az storage account show --name storageaccjimsonxyz --resource-group terraform-backend-rg --output none; then
      echo "Storage account not found. Creating..."
      az storage account create 
        --name storageaccjimsonxyz 
        --resource-group terraform-backend-rg 
        --sku Standard_RAGRS 
        --kind StorageV2 
        --location westeurope 
        --encryption-services blob 
        --https-only true 
        --allow-blob-public-access false 
        --min-tls-version TLS1_2
    else
      echo "Storage account exists."
    fi
  displayName: 'Create Storage Account and Resource Group'




# Download SSH Public Key
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'
    retryCount: '5'

# Initialize Terraform
- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-manager-service-connection'
    backendAzureRmTenantId: '4d143b55-605d-4af2-a581-12ee448bba20'
    backendAzureRmSubscriptionId: 'fbccdf0c-3db4-454b-a6f3-0713e306b7f5'
    # ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageaccjimsonxyz'
    backendAzureRmContainerName: 'storageaccjimsoncontainer'
    backendAzureRmKey: 'kuberenetes-dev.tfstate'
    allowTelemetryCollection: true

# Additional Tasks
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
